### ISSUE TITLE
kick-when-online: false Issue

### ISSUE THREAD

**Issue by kimtay168** [Limework/RedisBungee#113]
### intended behavior

da

### what the behavior you actually saw

ITs show You are already logged in in the tittle screen when we about to join

### Steps to reproduce

i dont have any video

### Velocity or Bungeecord Versions

Velocity

### RedisBungee Version & Redis Version

0.12.0

### Other

Can you fix that thats the issue its will blocked player to join even tho they are not online and its still show The Logged in thing

Thanks

**Comment by alaajel** [comment]
implementing command that will reset player data because sometimes if proxy is killed or redis somehow goes down player isn't updated and proxies will think its online.

**Comment by qamulex** [comment]
I have a similar problem. At this point, the player has not been able to log in for the last 20 hours, although there is no data about him stored in Redis.
![image](https://github.com/user-attachments/assets/9f2b8715-3d25-4b19-8819-f6349370d88f)
![image](https://github.com/user-attachments/assets/5371aca1-4173-450b-86df-22c7cb7327e6)

This problem, in fact, should not exist at all, since there is a correctionTask in ProxyDataManager
![image](https://github.com/user-attachments/assets/d00a7076-bc8d-4512-a418-58e91061b877)

**Comment by alaajel** [comment]
Its problem in players hash sets not sets in proxies
